### ISSUE TITLE
Make sender email configurable

### ISSUE THREAD

**Issue by nougad** [myfreeweb/freshcerts#2]
~~~
"#{Etc.getlogin}@#{Socket.gethostname}"
~~~
in https://github.com/myfreeweb/freshcerts/blob/master/common.rb#L103 is a good default but does not work for e.g. smtp smarthosts which expect a certain sender name.

I suggest another config option:

~~~.ruby
SENDER_EMAIL      = ENV['SENDER_EMAIL'] || "#{Etc.getlogin}@#{Socket.gethostname}"
~~~

and change https://github.com/myfreeweb/freshcerts/blob/master/common.rb#L103 

~~~.diff
-       from "#{Etc.getlogin}@#{Socket.gethostname}"
+       from SENDER_EMAIL
~~~

what do you think?

**Comment by myfreeweb** [comment]
Yeah, good. I thought this was a pull request already though :D
